service: data-process

frameworkVersion: "=3.28.1"

package:
  patterns:
    - '!./**'
    - 'functions/process_data.py'
    - 'utils/**'

custom:
  defaultStage: dev
  defaultRegion: us-east-1
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${opt:region, self:custom.defaultRegion}
  role: arn:aws:iam::891376954408:role/LabRole
  commentsDB: comments-db-${self:custom.stage}
  reviews_historyDB: reviews-history-db-${self:custom.stage}
  processedDataBucketName: ${self:service}-bucket-${self:custom.stage}

provider:
  name: aws
  runtime: python3.9
  region: ${self:custom.region}
  stage: ${self:custom.stage}
  deploymentBucket:
    name: tfm-deployment-bucket
  environment:
    region: ${self:custom.region}
    stage: ${self:custom.stage}
  ecr:
    images:
      data_process_pandas_img:
        path: "./"
        platform: linux/amd64

functions:
  process-restaurant-data:
    role: ${self:custom.role}
    description: 'Given a place and a platform process all the data obtained'
    timeout: 900
    image:
      name: data_process_pandas_img
      command:
        - functions.process_data.handler
    events:
      - schedule:
          name: process-trip-advisor-data-ab-chinchilla
          description: 'Invoke lambda that process the trip advisor obtained data from chinchilla'
          rate: cron(10 5 * * ? *)
          enabled: true
          input:
            trip_advisor_place_id: g1435704
            platform: trip_advisor
      - schedule:
          name: process-trip-advisor-data-ab
          description: 'Invoke lambda that process the trip advisor obtained data from albacete'
          rate: cron(11 5 * * ? *)
          enabled: true
          input:
            trip_advisor_place_id: g187486
            platform: trip_advisor
      - schedule:
          name: process-google-maps-data-ab-chinchilla
          description: 'Invoke lambda that process the google maps obtained data from chincilla'
          rate: cron(20 5 * * ? *)
          enabled: true
          input:
            trip_advisor_place_id: g1435704
            platform: google_maps
      - schedule:
          name: process-google-maps-data-ab
          description: 'Invoke lambda that process the google maps obtained data from albacete'
          rate: cron(21 5 * * ? *)
          enabled: true
          input:
            trip_advisor_place_id: g187486
            platform: google_maps
resources:
  Resources:
    ProcessedDataBucket:
        Type: AWS::S3::Bucket
        Properties:
          BucketName: ${self:custom.processedDataBucketName}
    CommentsDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.commentsDB}
        AttributeDefinitions:
          - AttributeName: place
            AttributeType: S
          - AttributeName: hash
            AttributeType: S
          - AttributeName: ts
            AttributeType: N
          - AttributeName: sentiment
            AttributeType: S
        KeySchema:
          - KeyType: HASH
            AttributeName: place
          - KeyType: RANGE
            AttributeName: hash
        GlobalSecondaryIndexes:
          - IndexName: PlaceByTs
            KeySchema:
              - AttributeName: place
                KeyType: HASH
              - AttributeName: ts
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: SentimentIndex
            KeySchema:
              - AttributeName: place
                KeyType: HASH
              - AttributeName: sentiment
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
    ReviewsHistoryDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.reviews_historyDB}
        AttributeDefinitions:
          - AttributeName: place
            AttributeType: S
          - AttributeName: detail
            AttributeType: S
        KeySchema:
          - KeyType: HASH
            AttributeName: place
          - KeyType: RANGE
            AttributeName: detail
        BillingMode: PAY_PER_REQUEST
