service: data-endpoints

frameworkVersion: "=3.28.1"

package:
  patterns:
    - '!./**'
    - 'functions/add_notifications.py'
    - 'functions/api.py'
    - 'functions/api_restaurant_data.py'
    - 'functions/api_notification_configs.py'
    - 'functions/api_restaurant_reviews.py'
    - 'functions/api_weekly_query.py'
    - 'functions/update_weekly_data.py'
    - 'functions/create_weekly_query.py'
    - 'utils/helper_wo_pandas.py'

custom:
  defaultStage: dev
  defaultRegion: us-east-1
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${opt:region, self:custom.defaultRegion}
  listRestaurantsDataDB: list-restaurants-data-db-${self:custom.stage}
  notificationConfigsDB: notification-configs-db-${self:custom.stage}
  notificationsDB: notifications-db-${self:custom.stage}

provider:
  name: aws
  runtime: python3.9
  region: ${self:custom.region}
  stage: ${self:custom.stage}
  environment:
    region: ${self:custom.region}
    stage: ${self:custom.stage}
  apiGateway:
    apiKeys:
      - name: restaurants-data-${self:custom.stage}
        description: Api key to obtain restaurant data

functions:
  update-weekly-data:
    role: arn:aws:iam::992675252360:role/LabRole
    description: 'Create the weekly query per place id'
    handler: functions/update_weekly_data.handler
    timeout: 900
    events:
      - schedule:
          name: schedule-weekly-data-update
          description: 'Invoke lambda that updates the weekly data in dynamodb Albacete'
          rate: cron(0 5 ? * SUN *)
          enabled: true
          input:
            trip_advisor_place_id: g187486

  create-weekly-query:
    role: arn:aws:iam::992675252360:role/LabRole
    description: 'Create the weekly query per place id'
    handler: functions/create_weekly_query.handler
    timeout: 900
    events:
      - schedule:
          name: schedule-creation-weekly-query
          description: 'Invoke lambda that creates the weekly query for Albacete'
          rate: cron(0 7 ? * SUN *)
          enabled: true
          input:
            trip_advisor_place_id: g187486

  create-user-notifications:
    role: arn:aws:iam::992675252360:role/LabRole
    description: 'Create user notifications based on configurations'
    handler: functions/add_notifications.handler
    timeout: 900
    events:
      - schedule:
          name: schedule-user-notifications
          description: 'Invoke lambda that creates notifications'
          rate: cron(0 8 ? * SUN *)
          enabled: true

  create-admin-notifications:
    role: arn:aws:iam::992675252360:role/LabRole
    description: 'Create admin notifications based on configurations'
    handler: functions/add_notifications.handler_admin
    timeout: 900
    events:
      - schedule:
          name: schedule-admin-notifications
          description: 'Invoke lambda that creates admin notifications'
          rate: cron(0 9 ? * SUN *)
          enabled: true


  api:
    role: arn:aws:iam::992675252360:role/LabRole
    description: 'Router to all endpoints'
    handler: functions/api.router
    events:
      - http:
          path: /data/combined
          method: get
          cors: true
      - http:
          path: /data/trip_advisor
          method: post
          cors: true
      - http:
          path: /data/google_maps
          method: post
          cors: true
      - http:
          path: /reviews/last
          method: post
          cors: true
      - http:
          path: /reviews/all
          method: post
          cors: true
      - http:
          path: /reviews/historical
          method: post
          cors: true
      - http:
          path: /notifications/configurations
          method: post
          cors: true
      - http:
          path: /notifications/configurations/new
          method: post
          cors: true
      - http:
          path: /notifications/configurations/delete
          method: post
          cors: true
      - http:
          path: /notifications
          method: post
          cors: true
  #        request:
  #          schemas:
  #            application/json: ${file(ass/swagger.yml):components.schemas.AlgoSubmitBody}

resources:
  Resources:
    ListRestaurantsDataDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.listRestaurantsDataDB}
        AttributeDefinitions:
          - AttributeName: ta_place_id
            AttributeType: S
          - AttributeName: ta_restaurant_id
            AttributeType: S
        KeySchema:
          - KeyType: HASH
            AttributeName: ta_place_id
          - KeyType: RANGE
            AttributeName: ta_restaurant_id
        BillingMode: PAY_PER_REQUEST
    NotificationConfigsDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.notificationConfigsDB}
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - KeyType: HASH
            AttributeName: username
          - KeyType: RANGE
            AttributeName: timestamp
        BillingMode: PAY_PER_REQUEST
    NotificationsDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.notificationsDB}
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - KeyType: HASH
            AttributeName: username
          - KeyType: RANGE
            AttributeName: timestamp
        BillingMode: PAY_PER_REQUEST